[package]
name = "provider-sdk"
version = "0.1.0"
edition = "2021"

[features]
default = [ ]
otel = ["opentelemetry", "tracing-opentelemetry", "opentelemetry-otlp"]

[dependencies]
async-nats = "0.30"
async-trait = "0.1"
atty = "0.2"
base64 = "0.21"
data-encoding = "2.3"
futures = "0.3"
lazy_static = "1.4"
nkeys = "0.3"
once_cell = "1.8"
opentelemetry = { version = "0.17", features = ["rt-tokio"], optional = true }
opentelemetry-otlp = { version = "0.10", features = ["http-proto", "reqwest-client"], optional = true }
rmp-serde = "1.1"
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
serde_json = "1"
sha2 = "0.10.2"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1.34", features = ["log"] }
tracing-futures = "0.2"
tracing-opentelemetry = { version = "0.17", optional = true }
tracing-subscriber = { version = "0.3.7", features = ["env-filter", "json"] }
uuid = { version = "1.4", features = ["v4"] }
wascap = "0.10"
