[package]
name = "wasmcloud-provider-sdk"
version = "0.1.0"

authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = [ ]
otel = ["opentelemetry", "tracing-opentelemetry", "opentelemetry-otlp"]

[dependencies]
# This is using all the concrete error types now so it needs to stay custom until we upgrade it in the workspace
async-nats = "0.30"
async-trait = { workspace = true }
atty = "0.2"
base64 = { workspace = true }
data-encoding = "2.3"
futures = { workspace = true }
lazy_static = { workspace = true }
nkeys = { workspace = true }
once_cell = { workspace = true }
opentelemetry = { version = "0.17", features = ["rt-tokio"], optional = true }
opentelemetry-otlp = { version = "0.10", features = ["http-proto", "reqwest-client"], optional = true }
rmp-serde = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_bytes = { workspace = true, features = ["default"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true, features = ["log"] }
tracing-futures = { workspace = true, features = ["default"] }
tracing-opentelemetry = { version = "0.17", optional = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json", "fmt"] }
uuid = { workspace = true, features = ["v4"] }
wascap = { workspace = true }
