[package]
name = "wasmcloud-provider-nats"
version = "0.17.3"

authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
async-nats = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
lazy_static = "1"
opentelemetry = "0.20"
serde = { workspace = true, features = ["derive"] }
serde_bytes = { workspace = true, features = ["std"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-futures = { workspace = true }
tracing-opentelemetry = "0.20"
wascap = { workspace = true }
wasmcloud-provider-sdk = { workspace = true, features = ["otel"] }
