[workspace]

[package]
# Pseudo-package whose dependencies are imported and buckified
name = "rust-third-party"
version = "0.0.0"
edition = "2021"
publish = false

# Dummy target to keep Cargo happy
[[bin]]
name = "dummy"
path = "dummy/main.rs"

[dependencies]
anstyle = { version = "1.0.10" }
anyhow = { version = "1" }
assert-json-diff = { version = "2" }
async-compression = { version = "0.3" }
async-nats = { version = "0.36" }
async-trait = { version = "0.1" }
aws-config = { version = "1.5" }
aws-sdk-s3 = { version = "1.60" }
aws-smithy-runtime = { version = "1.7" }
axum = { version = "0.7" }
axum-server = { version = "0.6" }
azure_core = { version = "0.20" }
azure_storage = { version = "0.20" }
azure_storage_blobs = { version = "0.20" }
backoff = { version = "0.4" }
base64 = { version = "0.22" }
bigdecimal = { version = "0.4" }
bit-vec = { version = "0.6" }
bytes = { version = "1" }
cap-std = { version = "3" }
cargo_metadata = { version = "0.18" }
cargo_toml = { version = "0.15" }
cbindgen = { version = "0.25" }
chrono = { version = "0.4" }
cidr = { version = "0.2" }
claims = { version = "0.7" }
clap = { version = "4" }
clap_complete = { version = "4" }
clap-markdown = { version = "0.1.4" }
cloudevents-sdk = { version = "0.7" }
command-group = { version = "5" }
config = { version = "0.13" }
console = { version = "0.15" }
crossterm = { version = "0.28.1" }
data-encoding = { version = "2" }
deadpool-postgres = { version = "0.13" }
dialoguer = { version = "0.11" }
docker_credential = { version = "1.3.1" }
etcetera = { version = "0.8" }
file-guard = { version = "0.2.0" }
futures = { version = "0.3" }
geo-types = { version = "0.7" }
heck = { version = "0.5" }
hex = { version = "0.4" }
http = { version = "1", default-features = false, features = ["std"] }
http-body = { version = "1" }
http-body-util = { version = "0.1" }
humantime = { version = "2" }
hyper = { version = "1" }
hyper-rustls = { version = "0.27" }
hyper-util = { version = "0.1" }
ignore = { version = "0.4" }
indicatif = { version = "0.17" }
kafka = { version = "0.10" }
names = { version = "0.14" }
nix = { version = "0.27" }
nkeys = { version = "0.4" }
normpath = { version = "1" }
notify = { version = "6" }
nuid = { version = "0.4" }
num = { version = "0.4" }
oci-client = { version = "0.14" }
oci-wasm = { version = "0.2.0" }
once_cell = { version = "1" }
opentelemetry = { version = "0.23" }
opentelemetry-appender-tracing = { version = "0.4" }
opentelemetry-otlp = { version = "0.16" }
opentelemetry_sdk = { version = "0.23" }
path-absolutize = { version = "3" }
path-clean = { version = "1" }
pg_bigdecimal = { version = "0.1" }
pin-project-lite = { version = "0.2" }
postgres-types = { version = "0.2" }
quote = { version = "1" }
rand = { version = "0.8" }
redis = { version = "0.25" }
regex = { version = "1" }
reqwest = { version = "0.12" }
# reqwest 0.11 is required by `wasmcloud-tracing` to allow customization of
# the HttpClient trait implementation for reqwest defined in `opentelemetry-http`,
# which is then used in `opentelemetry-otlp` to customize the http client used for
# interacting with OTEL collectors.
reqwest-0_11 = { package = "reqwest", version = "0.11" }
ring = { version = "0.17" }
rmp-serde = { version = "1" }
rmpv = { version = "1" }
rustls = { version = "0.23.11" }
rustls-native-certs = { version = "0.8" }
rustls-pemfile = { version = "2" }
rustversion = { version = "1.0" }
sanitize-filename = { version = "0.4" }
secrecy = { version = "0.8" }
semver = { version = "1" }
serde = { version = "1" }
serde-transcode = { version = "1" }
serde_bytes = { version = "0.11" }
serde_cbor = { version = "0.11" }
serde_json = { version = "1" }
serde_with = { version = "3" }
serde_yaml = { version = "0.9" }
serial_test = { version = "3" }
sha2 = { version = "0.10" }
sysinfo = { version = "0.27" }
tempfile = { version = "3" }
term-table = { version = "=1.3.2" }
termcolor = { version = "1" }
termsize = { version = "0.1" }
test-case = { version = "3" }
testcontainers = { version = "0.23" }
thiserror = { version = "1" }
time = { version = "0.3" }
tokio = { version = "1" }
tokio-postgres = { version = "0.7" }
tokio-postgres-rustls = { version = "0.13" }
tokio-stream = { version = "0.1" }
tokio-tar = { version = "0.3" }
tokio-util = { version = "0.7" }
toml = { version = "0.8" }
tower-http = { version = "0.5" }
tracing = { version = "0.1" }
tracing-appender = { version = "0.2" }
tracing-flame = { version = "0.2" }
tracing-futures = { version = "0.2" }
tracing-opentelemetry = { version = "0.24" }
tracing-subscriber = { version = "0.3" }
ulid = { version = "1" }
unicase = { version = "2.8.0" }
# We enable default features for URL by default here to help with the no-std
# transition for url. We should be able to remove default features and explicitly
# enable "std" above soon (tm).
#
# see: https://github.com/servo/rust-url/pull/831
url = { version = "2" }
uuid = { version = "1" }
vaultrs = { version = "0.7" }
wadm = { version = "0.18.0" }
wadm-client = { version = "0.7.1" }
wadm-types = { version = "0.7.1" }
walkdir = { version = "2" }
warp = { version = "0.3" }
wasi = { version = "0.13.3" }
wasm-pkg-client = { version = "0.8.3" }
wasm-pkg-core = { version = "0.8.3" }
wasi-preview1-component-adapter-provider = { version = "25" }
wasm-encoder = { version = "0.219" }
wasm-gen = { version = "0.1" }
wasmparser = { version = "0.219" }
wasmtime = { version = "25" }
wasmtime-wasi = { version = "25" }
wasmtime-wasi-http = { version = "25" }
wasmtime-wit-bindgen = { version = "25" }
wat = { version = "1" }
webpki-roots = { version = "0.26" }
weld-codegen = { version = "0.7" }
which = { version = "4" }
wit-bindgen = { version = "0.32", default-features = false, features = [
    "macros",
] }
wit-bindgen-core = { version = "0.33" }
wit-bindgen-go = { version = "0.32" }
wit-bindgen-wrpc = { version = "0.8" }
wit-component = { version = "0.219" }
wit-parser = { version = "0.219" }
wrpc-interface-blobstore = { version = "0.20" }
wrpc-interface-http = { version = "0.30" }
wrpc-runtime-wasmtime = { version = "0.24" }
wrpc-transport = { version = "0.28" }
wrpc-transport-nats = { version = "0.27.1", default-features = false, features = [
    "async-nats-0_36",
] }
