omit_targets = []
extra_srcs = []
omit_srcs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = []
omit_deps = []
cargo_env = true
linker_flags = []

[rustc_flags_select]

[env]
# This is a dumb thing because for some reason the build script remaps "OUT_DIR" to this var. But it is only used in a very specific circumstance.
DEBUG_OUTPUT_DIR = "/tmp"

[[buildscript]]
[buildscript.rustc_flags]
[[buildscript]]
[buildscript.gen_srcs]

[extra_mapped_srcs]

[platform_fixup]
